# Generated by Django 5.2.6 on 2025-09-10 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicnote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='son',
            new_name='song',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'song')},
        ),
    ]
