# Generated by Django 5.2.6 on 2025-09-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicnote', '0002_rename_son_review_song_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='deezer_id',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
