# Generated by Django 5.2.6 on 2025-09-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicnote', '0004_alter_song_deezer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='deezer_id',
            field=models.CharField(blank=True, default='0', null=True),
        ),
    ]
